global:
  scrape_interval: 15s

scrape_configs:
  - job_name: herddb
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9845
  - job_name: file-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9847
  - job_name: indexing-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9851
