{{- if and .Values.prometheus.enabled .Values.prometheus.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "herddb.fullname" . }}-prometheus
  labels:
    {{- include "herddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  minAvailable: {{ .Values.prometheus.pdb.minAvailable | default 1 }}
  selector:
    matchLabels:
      {{- include "herddb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
{{- end }}
