apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "herddb.fullname" . }}-server-config
  labels:
    {{- include "herddb.labels" . | nindent 4 }}
data:
  server.properties: |
    server.mode={{ .Values.server.mode }}
    server.host=0.0.0.0
    server.port={{ .Values.server.port }}
    server.base.dir=/opt/herddb/data
    server.log.dir=/opt/herddb/commitlog
    http.enable=true
    http.host=0.0.0.0
    http.port={{ .Values.server.httpPort }}
    {{- if eq .Values.server.storageMode "remote" }}
    server.storage.mode=remote
    remote.file.servers={{ include "herddb.remoteFileServers" . }}
    {{- end }}
    {{- if eq .Values.server.mode "cluster" }}
    server.zookeeper.address={{ include "herddb.zkAddress" . }}
    server.zookeeper.path=/herd
    server.bookkeeper.start=false
    server.bookkeeper.ensemble.size=1
    server.bookkeeper.write.quorum.size=1
    server.bookkeeper.ack.quorum.size=1
    {{- end }}
    {{- range $k, $v := .Values.server.extraConfig }}
    {{ $k }}={{ $v }}
    {{- end }}
