apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "herddb.fullname" . }}-server-config
  labels:
    {{- include "herddb.labels" . | nindent 4 }}
data:
  server.properties: |
    server.mode={{ .Values.server.mode }}
    server.host=0.0.0.0
    server.port={{ .Values.server.port }}
    server.base.dir=/opt/herddb/data
    server.log.dir=/opt/herddb/commitlog
    http.enable=true
    http.host=0.0.0.0
    http.port={{ .Values.server.httpPort }}
    {{- if eq .Values.server.mode "remote-file-service" }}
    remote.file.servers={{ include "herddb.remoteFileServers" . }}
    {{- end }}
    {{- range $k, $v := .Values.server.extraConfig }}
    {{ $k }}={{ $v }}
    {{- end }}
