#!/usr/bin/env bash
# recreate-pages-bucket.sh — Delete and recreate the HerdDB file-server pages
# bucket in the target GCS location.
#
# GCS buckets are regional; a bucket created in the wrong region incurs
# cross-region egress charges every time the file-server reads or writes a page.
# Use this script to move the bucket to the same region as the GKE cluster.
#
# Usage:
#   ./scripts/recreate-pages-bucket.sh [OPTIONS]
#
# Options:
#   --bucket <name>     GCS bucket name  (default: herddb-pages)
#   --location <loc>    Target GCS location  (default: europe-west4)
#   --storage-class <c> Storage class  (default: STANDARD)
#   --project <id>      GCP project ID  (default: from gcloud config)
#   --service-account <email>
#                       Service account to grant objectAdmin on the new bucket
#                       (default: herddb-gcs@<project>.iam.gserviceaccount.com)
#   --yes               Skip the confirmation prompt
#   --dry-run           Print what would happen without making changes
#   --help              Show this help
#
# What it does:
#   1. Checks the current bucket location.
#   2. Prompts for confirmation (unless --yes).
#   3. Deletes all objects in the bucket, then deletes the bucket itself.
#   4. Creates a new bucket with the same name in --location.
#   5. Grants the service account storage.objectAdmin on the new bucket.
#
# WARNING: all data in the bucket is permanently deleted.  For the pages
# bucket this is intentional — pages are regenerated by the file-server
# from the source data on the next benchmark run.  Never pass gs://herddb-datasets
# as --bucket; that bucket holds shared benchmark datasets that must not be wiped.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Inline helpers (no cluster connectivity needed so don't source common.sh)
timestamp() { date '+%Y%m%d-%H%M%S'; }
section()    { echo; echo "==> $*"; }

BUCKET="herddb-pages"
LOCATION="europe-west4"
STORAGE_CLASS="STANDARD"
PROJECT="$(gcloud config get-value project 2>/dev/null || echo "")"
SERVICE_ACCOUNT=""
YES=false
DRY_RUN=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bucket)          BUCKET="$2";          shift 2 ;;
    --location)        LOCATION="$2";        shift 2 ;;
    --storage-class)   STORAGE_CLASS="$2";   shift 2 ;;
    --project)         PROJECT="$2";         shift 2 ;;
    --service-account) SERVICE_ACCOUNT="$2"; shift 2 ;;
    --yes)             YES=true;             shift   ;;
    --dry-run)         DRY_RUN=true;         shift   ;;
    --help|-h)
      sed -n '2,31p' "$0" | sed 's/^# //'
      exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# Safety guard: never touch the datasets bucket
if [[ "$BUCKET" == "herddb-datasets" ]]; then
  echo "ERROR: refusing to touch gs://herddb-datasets (shared datasets bucket)." >&2
  exit 1
fi

if [[ -z "$PROJECT" ]]; then
  echo "ERROR: GCP project not set. Pass --project <id> or: gcloud config set project <id>" >&2
  exit 1
fi

if [[ -z "$SERVICE_ACCOUNT" ]]; then
  SERVICE_ACCOUNT="herddb-gcs@${PROJECT}.iam.gserviceaccount.com"
fi

# ── Show plan ────────────────────────────────────────────────────────────────
section "Recreate GCS pages bucket"
echo "  Bucket:          gs://$BUCKET"
echo "  Target location: $LOCATION"
echo "  Storage class:   $STORAGE_CLASS"
echo "  Project:         $PROJECT"
echo "  Service account: $SERVICE_ACCOUNT"

CURRENT_LOC="(does not exist)"
if gcloud storage buckets describe "gs://$BUCKET" --format="value(location)" \
     --project="$PROJECT" &>/dev/null; then
  CURRENT_LOC="$(gcloud storage buckets describe "gs://$BUCKET" \
    --format='value(location)' --project="$PROJECT" 2>/dev/null)"
fi
echo "  Current location: $CURRENT_LOC"
echo ""

if $DRY_RUN; then
  echo "[DRY RUN] Would delete gs://${BUCKET} (all objects + bucket) then recreate in ${LOCATION}."
  exit 0
fi

# ── Confirmation ─────────────────────────────────────────────────────────────
if ! $YES; then
  echo "WARNING: This will permanently delete ALL objects in gs://$BUCKET and"
  echo "         recreate the bucket in $LOCATION."
  echo ""
  read -r -p "  Type the bucket name to confirm deletion: " CONFIRM
  if [[ "$CONFIRM" != "$BUCKET" ]]; then
    echo "Aborted (input did not match bucket name)." >&2
    exit 1
  fi
fi

# ── Delete existing bucket ───────────────────────────────────────────────────
if gcloud storage buckets describe "gs://$BUCKET" --project="$PROJECT" &>/dev/null; then
  section "Deleting all objects in gs://$BUCKET"
  # Use -r (recursive) with ** glob; tolerate empty bucket (|| true)
  gcloud storage rm --recursive "gs://${BUCKET}/**" 2>/dev/null || true

  section "Deleting bucket gs://$BUCKET"
  gcloud storage buckets delete "gs://$BUCKET" --project="$PROJECT"
else
  echo "  Bucket gs://$BUCKET does not exist — skipping delete."
fi

# ── Create new bucket ────────────────────────────────────────────────────────
section "Creating gs://$BUCKET in $LOCATION ($STORAGE_CLASS)"
gcloud storage buckets create "gs://$BUCKET" \
  --project="$PROJECT" \
  --location="$LOCATION" \
  --default-storage-class="$STORAGE_CLASS" \
  --uniform-bucket-level-access

# ── Grant IAM ────────────────────────────────────────────────────────────────
# Retry up to 10 times with 5-second backoff: GCS metadata propagation after a
# fresh bucket creation can take a few seconds and causes transient 404 errors
# from the bucket-level IAM API even though the bucket is already visible via ls.
section "Granting storage.objectAdmin to $SERVICE_ACCOUNT (with retry)"
IAM_OK=false
for attempt in $(seq 1 10); do
  if gcloud projects add-iam-policy-binding "$PROJECT" \
       --member="serviceAccount:$SERVICE_ACCOUNT" \
       --role="roles/storage.objectAdmin" \
       --condition=None &>/dev/null; then
    IAM_OK=true
    echo "  IAM binding applied (attempt $attempt)."
    break
  fi
  echo "  Attempt $attempt failed, retrying in 5s..."
  sleep 5
done
if ! $IAM_OK; then
  echo "ERROR: failed to apply IAM binding after 10 attempts." >&2
  exit 1
fi

section "Verifying"
gcloud storage buckets describe "gs://$BUCKET" \
  --format="table(name,location,storageClass)" \
  --project="$PROJECT"

echo ""
echo "BUCKET=gs://$BUCKET"
echo "LOCATION=$LOCATION"
echo "Done. Update fileServer.s3.bucket in values.yaml if the bucket name changed."
