{{- if .Values.minio.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "herddb.fullname" . }}-minio
  labels:
    {{- include "herddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  serviceName: {{ include "herddb.fullname" . }}-minio-headless
  replicas: 1
  selector:
    matchLabels:
      {{- include "herddb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "herddb.labels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          imagePullPolicy: IfNotPresent
          command: ["minio", "server", "/data", "--address", ":{{ .Values.minio.port }}", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.minio.adminUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.minio.adminPassword | quote }}
          ports:
            - name: s3-api
              containerPort: {{ .Values.minio.port }}
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: s3-api
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: s3-api
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.minio.storage.storageClass }}
        storageClassName: {{ .Values.minio.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.minio.storage.size }}
{{- end }}
