apiVersion: v1
kind: Service
metadata:
  name: {{ include "herddb.fullname" . }}-server
  labels:
    {{- include "herddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  clusterIP: None
  selector:
    {{- include "herddb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: jdbc
      port: {{ .Values.server.port }}
      targetPort: jdbc
    - name: http
      port: {{ .Values.server.httpPort }}
      targetPort: http
