#
# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for additional
# information regarding copyright ownership.  The ASF licenses this file to you
# under the Apache License, Version 2.0 (the # "License"); you may not use this
# file except in compliance with the License.  You may obtain a copy of the License
# at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
name: Java CI - Kubernetes tests
on:
  pull_request:
  push:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  MAVEN_OPTS: -Dmaven.artifact.threads=4 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn  -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 25'
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'
      - name: 'Cache Maven packages'
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: 'cache'
          restore-keys: 'cache'
      - name: 'Checkout jvector'
        uses: actions/checkout@v4
        with:
          repository: eolivelli/jvector
          ref: feature/bytebuffer-zero-copy-vectors
          path: jvector
      - name: 'Build jvector'
        run: mvn -B install -DskipTests -Drat.skip=true --file jvector/pom.xml && rm -rf jvector
      - name: 'Build with Maven'
        run: mvn -B install -DskipTests --file pom.xml -Pci
      - name: 'Build docker images'
        run: mvn -B -pl herddb-docker --file pom.xml package -Ddocker
      - name: 'Install Helm'
        uses: azure/setup-helm@v4
      - name: 'Install helm-unittest plugin'
        run: helm plugin install --verify=false https://github.com/helm-unittest/helm-unittest.git
      - name: 'Helm lint'
        run: helm lint herddb-kubernetes/src/main/helm/herddb
      - name: 'Helm unit tests'
        run: helm unittest herddb-kubernetes/src/main/helm/herddb
      - name: 'Run Kubernetes tests'
        run: mvn -B verify -pl herddb-kubernetes --file pom.xml -Pkubernetes
      - name: 'Remove Snapshots Before Caching'
        run: find ~/.m2 -name '*SNAPSHOT' | xargs rm -Rf
